//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Distributer
    {
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Distributer()
        {
            this.Invoices = new HashSet<Invoice>();
        }
        [Display(Name = "Distributer")]
        public int DistributerId { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Distributer Name")]
        public string Name { get; set; }
        [Display(Name = "Distributer Status")]
        public byte Status { get; set; }
        [Display(Name = "User")]
        public int UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual User User { get; set; }
    }
}
