//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class InvoiceItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceItem()
        {
            this.Receipts = new HashSet<Receipt>();
        }
        
        public int InvoiceItemID { get; set; }
        [Display(Name = "Invoice")]
        public int InvoiceID { get; set; }
        [Display(Name = "Item")]
        public int ItemID { get; set; }
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
        [Column(TypeName = "money")]
        [Display(Name = "Unit Cost")]
        public decimal Cost { get; set; }
        [Column(TypeName = "money")]
        [Display(Name = "Extended Cost")]
        public decimal ExtendedCost { get { return Quantity * Cost; } set { } }
        [Display(Name = "User")]
        public int UserID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual User User { get; set; }
    }
}
