//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    using System.Linq;

    public partial class Item 
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

       
        public Item()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
            this.Spoilages = new HashSet<Spoilage>();
            this.UsedItems = new HashSet<UsedItem>();
        }

        [Display(Name = "Item")]
        public int ItemID { get; set; }
        [Display(Name = "Retail Name")]
        public string Name { get; set; }
        [Column(TypeName = "money")]
        [Display(Name = "Retail Price")]
        [Range(0.01, 1000.00,
            ErrorMessage = "Price must be between 0.01 and 1000.00")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }


       


        [Display(Name = "Item Status")]
       // public byte Status { get; set; }


        public byte Status
        {
            get
            {
                if (Quantity <= 0)
                {
                    return Status = 0;
                }
                else { return 1; }

            }

            set { }

        }


        [Display(Name = "Category Name")]
        public int CategoryID { get; set; }
        [Column(TypeName = "date")]
        [Display(Name = "Date Added")]
        [DataType(DataType.Date)]
        public System.DateTime DateAdded { get; set; }
        [Column(TypeName = "date")]
        [Display(Name = "Experation Date")]
        [DataType(DataType.Date)]
        public System.DateTime ExperationDate { get; set; }
        public decimal Total { get { return Quantity * Price; } set { } }
        public int UserID { get; set; }



        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spoilage> Spoilages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsedItem> UsedItems { get; set; }
        public virtual User User { get; set; }
    }

}
