//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Receipt 
    {
        [Key]
        [Column(Order = 0)]
        public int ReceiptID { get; set; }
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
        [Column(TypeName = "money")]
        [Display(Name = "Cost")]
        public decimal Cost { get; set; }
        [Column(TypeName = "money")]
        [Display(Name = "Total Cost")]
        public decimal TotalCost { get { return Quantity * Cost; } set { } }
        [Column(TypeName = "date")]
        [Display(Name = "Receipt Date")]
        [DataType(DataType.Date)]
        public System.DateTime ReceiptDate { get; set; }
        [Display(Name = "Invoice Item Number")]
        public int InvoiceItemID { get; set; }
        [Display(Name = "User")]
        public int UserID { get; set; }
    
        public virtual InvoiceItem InvoiceItem { get; set; }

        public virtual User User { get; set; }
    }
}
