//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Spoilage
    {
        public int SpoilageID { get; set; }
        [Column(TypeName = "date")]
        [Display(Name = "Date Spoiled")]
        [DataType(DataType.Date)]
        public System.DateTime DateSpoiled { get; set; }
        [Display(Name = "Reason For Spoilage?")]
        public string Reason { get; set; }
        [Display(Name = "Quantity")]
        public int Quantity { get; set; }
        [Display(Name = "Item Name")]
        public int ItemID { get; set; }
        [Display(Name = "User")]
        public int UserID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
