//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test22.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    public partial class UsedItem
    {
        public int UsedID { get; set; }
        [Display(Name = " Item")]
        public int ItemID { get; set; }
        [Display(Name = " Quantity")]
        public int Quantity { get; set; }
        [Column(TypeName = "money")]
        [Display(Name = "Unity Cost")]
        public decimal UnitCost { get; set; }
        [Column(TypeName = "money")]
        [Display(Name = "Extended Cost")]
        public decimal ExtendedCost { get { return Quantity * UnitCost; } set { } }
        [Column(TypeName = "date")]
        [Display(Name = "Date Used")]
        [DataType(DataType.Date)]
        public System.DateTime DateUsed { get; set; }
        public int UserID { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
    }
}
